# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Programmer.new
tagline:          Taking it One Line at A Time
url:              http://strohy1210.github.io/
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
